### ISSUE TITLE
updatePomVersion.py error with biosem-event-extractor

### ISSUE THREAD

**Issue by khituras** [JULIELab/jcore-misc#1]
The updatePomVersion.py script is not able to complete the operation on jcore-dependencies due to an error with the pom of biosem:

> updatePomVersion.py /Volumes/OUTERSPACE/Coding/git/jcore-dependencies/ 2.2.0-SNAPSHOT 2.1.0
> [parent POM] base project changed version:
>      from 2.1.0 to 2.2.0-SNAPSHOT
> [parent POM] aliasi-lingpipe changed version:
>      from 2.1.0 to 2.2.0-SNAPSHOT
> [self version] aliasi-lingpipe: removed individual version.
> [parent POM] biosem-event-extractor changed version:
>      from 2.1.0 to 2.2.0-SNAPSHOT
> [self version] biosem-event-extractor: removed individual version.
> Traceback (most recent call last):
>   File "updatePomVersion.py", line 87, in <module>
>     default_namespace=xlmns[1:-1])
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 817, in write
>     self._root, encoding, default_namespace
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 891, in _namespaces
>     add_qname(key)
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 865, in add_qname
>     "cannot use non-qualified names with "
> ValueError: cannot use non-qualified names with default_namespace option

**Comment by fmatthies** [comment]
could it be due to Python2.7 vs. 3.5?
Your trace shows references to 2.7 libs.

**Comment by khituras** [comment]
Yes, you’re right. I actually installed 3.5 but did not activate it. And for the other files, everything went fine. OK sorry, my bad!

**Comment by fmatthies** [comment]
At least we now know, that we need Python3.5 ;)
