### ISSUE TITLE
cpe-build-script: TS hierarchy

### ISSUE THREAD

**Issue by fmatthies** [JULIELab/jcore-misc#3]
cpe builder need some minimal ts hierarchy check:
e.g. BioSEM Relation Extractor needs 'Gene' as in-capability & JNET provides EntityMention
--> they are not compatible as seen by the cpe-builder because it's no exact match

**Comment by khituras** [comment]
While these issues have been moved to https://github.com/JULIELab/jcore-pipeline-modules, this exact capability is still not fulfilled their, either. Closing this here.
